# Generated by Django 5.0.6 on 2025-05-23 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
